// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-VFjPbl0FAA_ABFbkwqR8lhx0aMMaSsw',
    appId: '1:911881811812:web:aecd95e17ba56804476c71',
    messagingSenderId: '911881811812',
    projectId: 'exult-shop',
    authDomain: 'exult-shop.firebaseapp.com',
    storageBucket: 'exult-shop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDysF2uvkCf0QzScLC9GvmsfGrjA8NYKq8',
    appId: '1:911881811812:android:c9a879d089778eb1476c71',
    messagingSenderId: '911881811812',
    projectId: 'exult-shop',
    storageBucket: 'exult-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlGTseWCatNmFTDgZ6cneh1rZ3q0CQOvc',
    appId: '1:911881811812:ios:7ca324623fa395e1476c71',
    messagingSenderId: '911881811812',
    projectId: 'exult-shop',
    storageBucket: 'exult-shop.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlGTseWCatNmFTDgZ6cneh1rZ3q0CQOvc',
    appId: '1:911881811812:ios:7ca324623fa395e1476c71',
    messagingSenderId: '911881811812',
    projectId: 'exult-shop',
    storageBucket: 'exult-shop.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-VFjPbl0FAA_ABFbkwqR8lhx0aMMaSsw',
    appId: '1:911881811812:web:85769cc9a0a40434476c71',
    messagingSenderId: '911881811812',
    projectId: 'exult-shop',
    authDomain: 'exult-shop.firebaseapp.com',
    storageBucket: 'exult-shop.firebasestorage.app',
  );

}