// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHa5HwcAwIyOE9TYuTUeOlX--RtdR9gN8',
    appId: '1:699709353509:web:3b117d4c781fd7705419cc',
    messagingSenderId: '699709353509',
    projectId: 'coffeeshop-3270e',
    authDomain: 'coffeeshop-3270e.firebaseapp.com',
    storageBucket: 'coffeeshop-3270e.firebasestorage.app',
    measurementId: 'G-XE8V7VSG5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCvoTD7SbBmOlOhUga0psaOMkZ05-uvIU',
    appId: '1:699709353509:android:5961acb777abc0855419cc',
    messagingSenderId: '699709353509',
    projectId: 'coffeeshop-3270e',
    storageBucket: 'coffeeshop-3270e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARnoP_c-3NHE5c1cbcK-AFxuZtmy2gMrs',
    appId: '1:699709353509:ios:162fb12aed324d6c5419cc',
    messagingSenderId: '699709353509',
    projectId: 'coffeeshop-3270e',
    storageBucket: 'coffeeshop-3270e.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARnoP_c-3NHE5c1cbcK-AFxuZtmy2gMrs',
    appId: '1:699709353509:ios:162fb12aed324d6c5419cc',
    messagingSenderId: '699709353509',
    projectId: 'coffeeshop-3270e',
    storageBucket: 'coffeeshop-3270e.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHa5HwcAwIyOE9TYuTUeOlX--RtdR9gN8',
    appId: '1:699709353509:web:1a9ebeb7fe862fe35419cc',
    messagingSenderId: '699709353509',
    projectId: 'coffeeshop-3270e',
    authDomain: 'coffeeshop-3270e.firebaseapp.com',
    storageBucket: 'coffeeshop-3270e.firebasestorage.app',
    measurementId: 'G-1YN3R964WS',
  );
}
